# Enhanced architecture configuration for funcqc
# Based on feedback for allow-based rules with comprehensive layer coverage

layers:
  # Entry points and user interfaces
  cli:
    - "src/cli.ts"
    - "src/cli/**"
  
  # Application orchestration and use case coordination
  orchestration:
    - "src/use-cases/**"
  
  # Specialized analysis engines and algorithms
  analysis:
    - "src/analyzers/**"
    - "src/similarity/**"
  
  # Core domain logic and business rules
  domain:
    - "src/core/**"
    - "src/metrics/**"
    - "src/refactoring/**"
  
  # External service integrations and background processing
  services:
    - "src/services/**"
    - "src/workers/**"
  
  # Data persistence and database operations
  storage:
    - "src/storage/**"
    - "src/migrations/**"
  
  # Infrastructure, configuration and static data
  infrastructure:
    - "src/config/**"
    - "src/schemas/**"
    - "src/data/**"
  
  # Pure utility functions and tools
  utils:
    - "src/utils/**"
    - "src/tools/**"
    - "src/visualization/**"
  
  # Type definitions (completely independent)
  types:
    - "src/types/**"

rules:
  # CLI layer: Entry point, can depend on orchestration and infrastructure
  - type: allow
    from: "cli"
    to: ["orchestration", "infrastructure", "utils", "types"]
    description: "CLI can orchestrate use cases and access configuration"

  # Orchestration layer: Coordinates domain operations
  - type: allow
    from: "orchestration"
    to: ["analysis", "domain", "services", "infrastructure", "utils", "types"]
    description: "Use cases orchestrate analysis, domain logic, and services"

  # Analysis layer: Specialized engines, can use domain logic and services
  - type: allow
    from: "analysis"
    to: ["domain", "services", "storage", "infrastructure", "utils", "types"]
    description: "Analysis engines can use domain logic and external services"

  # Domain layer: Core business logic, can use storage and utilities
  - type: allow
    from: "domain"
    to: ["storage", "infrastructure", "utils", "types"]
    description: "Domain logic can persist data and use utilities"

  # Services layer: External integrations, can use storage and utilities
  - type: allow
    from: "services"
    to: ["storage", "infrastructure", "utils", "types"]
    description: "Services can persist data and use configuration"

  # Storage layer: Data persistence, can use infrastructure and utilities
  - type: allow
    from: "storage"
    to: ["infrastructure", "utils", "types"]
    description: "Storage can use configuration and utilities"

  # Infrastructure layer: Configuration and schemas, can use utilities
  - type: allow
    from: "infrastructure"
    to: ["utils", "types"]
    description: "Infrastructure can use utilities for configuration processing"

  # Utils layer: Can only depend on types
  - type: allow
    from: "utils"
    to: ["types"]
    description: "Utilities are pure functions that only use types"

  # Types layer: Completely independent
  - type: forbid
    from: "types"
    to: "*"
    description: "Types must be completely independent and self-contained"
    severity: error

  # Prevent upward dependencies (architectural violations)
  - type: forbid
    from: ["orchestration", "analysis", "domain", "services", "storage", "infrastructure", "utils"]
    to: "cli"
    description: "Lower layers cannot depend on CLI entry points"
    severity: error

  - type: forbid
    from: ["analysis", "domain", "services", "storage", "infrastructure", "utils"]
    to: "orchestration"
    description: "Lower layers cannot depend on orchestration layer"
    severity: error

settings:
  allowSameLayer: true
  strictMode: true
  defaultSeverity: error
  ignoreExternal: true